import WarpRouter from 'warp-router'
import {Configuration} from "../../src/Configuration";
import {Route} from "../../src/Route";
import {myFunction} from "./page2";

function createDemo() {
  const configuration = new Configuration()
  configuration.defaultRoute = ""
  const router = new WarpRouter('.container', configuration)
  let routes: Map<string,Route> = new Map()
  routes.set("", new Route((): string => {
    return "This is the home page"
  }))
  routes.set("#page1", new Route((): void => {
      router.hostElement.innerHTML = `<p>This content was generated by a routing function page 1</p>`
    }
  ))
  routes.set("#page2", new Route((): void => {
     myFunction(router.hostElement)
    }
  ))

  router.setRoutes(routes)


  router.attach()
}

createDemo()

