import WarpRouter from 'warp-router'
import {Configuration} from "../../src/Configuration";
import {Route} from "../../src/Route";

function createDemo() {
  const configuration = new Configuration()
  configuration.defaultRoute = ""
  const router = new WarpRouter('.container', configuration)
  let routes: Map<string,Route> = new Map()
  routes.set("", new Route(function () {
    return "This is the home page"
  }))
  routes.set("#page1", new Route(() => {
    router.hostElement.innerHTML = `<p>This content was generated by a routing function</p>`
    }
  ))

  router.setRoutes(routes)
}

createDemo()

