export const CreateComponent = (hostElement) => {
  hostElement.innerHTML = `
         <p>This content was generated by a routing function page 2</p>
         <button id="page2btn">This button will do something</button>
      `

  function addListeners() {
    document.querySelector('#page2btn').addEventListener('click', function () {
      alert("It worked")
    })
  }

  addListeners()
}
